apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpass-secret-admin"}},"mappingMethod":"claim","name":"admin_htpasswd_provider","type":"HTPasswd"}]}}
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret-admin
      mappingMethod: claim
      name: admin_htpasswd_provider
      type: HTPasswd
    - htpasswd:
        fileData:
          name: htpasswd-secret
      mappingMethod: claim
      name: gitops_htpasswd_provider
      type: HTPasswd

